font_size               15
font_family             JetBrains Mono

window_margin_width     0

tab_bar_style powerline

shell distrobox enter fedora1

map ctrl+shift+t new_tab_with_cwd

env TERMINAL=kitty

include colors.conf
