if has("syntax")
	syntax on
endif

nnoremap qt :vert term<CR><C-w><C-r>

noremap qq <Esc>:q<CR>
noremap qqa <Esc>:qa<CR>
noremap qqq <Esc>:q!<CR>
noremap qqqa <Esc>:qa!<CR>

noremap vs <Esc>:e $MYVIMRC<CR>

inoremap qw <Esc>:w<CR>i<Right>
nnoremap qw :w<CR>

inoremap ii <Esc><Right>

set number

call plug#begin()
	Plug 'neoclide/coc-prettier'
	Plug 'neoclide/coc.nvim'
	
	Plug 'lervag/vimtex'
	
	Plug 'jiangmiao/auto-pairs'

	Plug 'itchyny/lightline.vim'
	Plug 'altercation/vim-colors-solarized'
	Plug 'scrooloose/nerdtree'
call plug#end()

noremap qf <Esc>:NERDTreeToggle<CR>

set encoding=UTF-8
set tabstop=4

set background=dark
set laststatus=2
set noshowmode
let g:lightline = {
	\ 'colorscheme': 'solarized',
	\ }

colors solarized

