if has("syntax")
	syntax on
endif

nnoremap qt :vert term<CR><C-w><C-r>

nnoremap s5 :so %<CR>

noremap qq <Esc> :q<CR>
noremap qqq <Esc> :q!<CR>
noremap vs <Esc>:e $MYVIMRC<CR>
inoremap qw <Esc>:w<CR>i<Right>
nnoremap qw :w<CR>
inoremap ii <Esc><Right>

set number

call plug#begin()
	Plug 'itchyny/lightline.vim'
	Plug 'altercation/vim-colors-solarized'
	Plug 'calincru/flex-bison-syntax'
	Plug 'scrooloose/syntastic'
	Plug 'othree/html5.vim'
	Plug 'ryanoasis/vim-devicons'
	Plug 'scrooloose/nerdtree'
	Plug 'valloric/youcompleteme'
	Plug 'jiangmiao/auto-pairs'
	Plug 'jrozner/vim-antlr'
	Plug 'dart-lang/dart-vim-plugin'
	Plug 'leafgarland/typescript-vim'
call plug#end()

noremap qf <Esc>:NERDTreeToggle<CR>

set encoding=UTF-8
set tabstop=4

set background=dark
set laststatus=2
set noshowmode
let g:lightline = {
	\ 'colorscheme': 'solarized',
	\ }

colors solarized

