#!/bin/bash

BASEDIR=$(dirname "$0")
source $BASEDIR/basic-setup

mkdir -p ~/.xmonad
mkdir -p ~/.config/xmobar
cp $FILEDIR/.xmonad/xmonad-pc.hs ~/.xmonad/xmonad.hs
cp $FILEDIR/.config/xmobar/xmobar-pc.config ~/.config/xmobar/xmobar.config

# setup nvidia driver
# ipkg nvidia
sudo reboot
