#!/bin/bash

BASEDIR=$(dirname "$0")
source $BASEDIR/basic-setup

mkdir -p ~/.xmonad
mkdir -p ~/.config/xmobar
cp $FILEDIR/.xmonad/xmonad-laptop.hs ~/.xmonad/xmonad.hs
cp $FILEDIR/.config/xmobar/xmobar-laptop.config ~/.config/xmobar/xmobar.config

# setup backlight
ipkg_yay light

sudo sh -c "printf \"#\!/bin/sh\nchown $USER /sys/class/backlight/amdgpu_bl0/brightness\nexit 0\n\" > /etc/rc.local"

sudo reboot
