#!/bin/bash

BASEDIR=$(dirname "$0")
source $BASEDIR/basic-setup

mkdir -p ~/.xmonad
mkdir -p ~/.config/xmobar
cp $FILEDIR/.xmonad/xmonad-pc.hs ~/.xmonad/xmonad.hs
cp $FILEDIR/.config/xmobar/xmobar-pc.config ~/.config/xmobar/xmobar.config

# download nvidia driver
mkdir -p ~/Downloads
cd ~/Downloads
wget https://de.download.nvidia.com/XFree86/Linux-x86_64/470.57.02/NVIDIA-Linux-x86_64-470.57.02.run

sudo reboot
