theme = "custom"

[editor]
line-number = "relative"
whitespace.render = "all"
soft-wrap.enable = true
soft-wrap.max-wrap = 100
# lsp.display-inlay-hints = true
lsp.inlay-hints-length-limit = 20

end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

B = ":sh git log -n 5 --format='format:%%h %%an (%%ar) \"%%s\"' --no-patch -L %{cursor_line},+1:%{buffer_name}"


